name: pak_trader
description: Offline Invoice Generator for Pak Trader
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
